services:

  nodejs:
    build:
      context: .
      dockerfile: Dockerfile.nodejs
    container_name: nodejs
    hostname: nodejs
    volumes:
      - ./nodejs/data:/app
    ports:
      - "3000:3000"
    networks:
      - mongo-net

  mongodb:
    build:
      context: .
      dockerfile: Dockerfile.mongodb
    container_name: mongodb
    hostname: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass123
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb/data:/data/db
    networks:
      - mongo-net

networks:
  mongo-net:
    driver: bridge
